GET http://localhost:3306/

###
POST http://localhost:3306/login
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "testezao"
}

###
POST http://localhost:3306/signup
Content-Type: application/json

{
    "name": "nomedaora",
    "email": "emaildaora@gmail.com",
    "password": "senhadaora"
}